name: Deploy to GitHub Pages

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
    
    - name: Install dependencies
      run: npm install
    
    - name: Run final tests
      run: npm run test
    
    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./
        publish_branch: gh-pages
    
    - name: Verify deployment
      run: |
        echo "Deployment complete!"
        echo "Site should be live at: https://benziongoldstein.github.io/math_web_app/"
    
    - name: Create deployment notification
      uses: actions/github-script@v6
      with:
        script: |
          const commit = context.payload.head_commit;
          console.log(`✅ Deployed commit: ${commit.message}`);
          console.log(`🚀 Live at: https://benziongoldstein.github.io/math_web_app/`);

